import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { polyfillNode } from "esbuild-plugin-polyfill-node";
import inlineWorker from "esbuild-plugin-inline-worker";
import { copyFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Copy sql.js wasm file to plugin folder for runtime loading
try {
	copyFileSync(
		"node_modules/sql.js/dist/sql-wasm-browser.wasm",
		"sql-wasm-browser.wasm"
	);
} catch (e) {
	console.warn("Warning: Failed to copy sql-wasm-browser.wasm:", e.message);
}

const polyfillPlugin = polyfillNode({
	globals: false,
	polyfills: {
		stream: true,
	},
});

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"onnxruntime-node",
		"sharp",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	platform: "browser",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	loader: { ".webp": "dataurl" },
	plugins: [inlineWorker(), polyfillPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
await new Promise(() => {});
